force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <label>Producer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Philips</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PW_ProductsContentPage.cls
public without sharing class PW_ProductsContentPage {
        @AuraEnabled(cacheable=true)
        public static List<PricebookEntry> getNewestProduct(Integer offsetNumber){
                return [SELECT Product2.Name, Product2.DisplayUrl, Product2.Model__c, Product2.Family, Product2.Producer__c, UnitPrice, Product2.CreatedDate 
                        FROM PricebookEntry WHERE Product2.CreatedDate >= LAST_N_DAYS:7 AND Product2.IsActive = true LIMIT 3 OFFSET :offsetNumber];
        }

        @AuraEnabled(cacheable = true)
        public static List<AggregateResult> getNumberOfRecords() {
                return [SELECT COUNT(Id) totalRecords FROM Product2 WHERE CreatedDate >= LAST_N_DAYS:7 AND Product2.IsActive=true];
        }
}