force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <label>Producer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Philips</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PW_RecentlyViewedProducts.cls
public without sharing class PW_RecentlyViewedProducts {

    @AuraEnabled(cacheable=true)
    public static List<Product2> getRecentlyViewedProducts(Integer offsetNumber){
        List<RecentlyViewed> recentlyViewedProductsId = [SELECT Id FROM RecentlyViewed WHERE Type='Product2' AND LastViewedDate = LAST_N_DAYS:7 ORDER BY LastViewedDate DESC LIMIT 5];
        Set<Id> productIds = new Set<Id>();
        for (RecentlyViewed s : recentlyViewedProductsId) {
            productIds.add(s.Id);
        }
        return [SELECT Id, Name, Model__c, Family, Producer__c, DisplayUrl, Available__c FROM Product2 WHERE Id IN:productIds ORDER BY Name LIMIT 1 OFFSET :offsetNumber];
    }

    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getNumberOfRecords() {
        return [SELECT COUNT(Id) totalRecords FROM RecentlyViewed  WHERE Type='Product2' AND LastViewedDate = LAST_N_DAYS:7];
    }
}