force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <label>Producer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Philips</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/customSearchProductTest.cls
@IsTest
public with sharing class customSearchProductTest {

    @TestSetup
    public static void testSetup() {
        Product2 productTest = new Product2(Name='CPU i5',Model__c='i5-4434',Producer__c='Intel',ProductCode='G88E',Available__c=true,Family='CPU');
        Product2 productTest2 = new Product2(Name='GPU AMD',Model__c='i5-4334',Producer__c='AMD',ProductCode='G82E',Available__c=true,Family='GPU');
        insert productTest2;
        insert productTest;
    }

    @IsTest
    public static void shouldReturnProductFromDatabaseWithConditions() {
        Product2 product = [SELECT Id, Name, Model__c, Producer__c, ProductCode, Available__c, Family FROM Product2 WHERE ProductCode='G88E'];
        List<Product2> productListFromDatabase = customSearchSobject.getProducts('CPU i5','i5-4434','G88E','Intel','CPU');
        Product2 productFromDatabse = productListFromDatabase.get(0);
        System.assertEquals(product.Id,productFromDatabse.Id);
    }


    @IsTest
    public static void shouldReturnProductFromDatabaseWithConditions2() {
        Product2 product = [SELECT Id, Name, Model__c, Producer__c, ProductCode, Available__c, Family FROM Product2 WHERE ProductCode='G88E'];
        List<Product2> productListFromDatabase = customSearchSobject.getProducts('GPU AMD','i5-4334','G82E','AMD','GPU');
        Product2 productFromDatabse = productListFromDatabase.get(0);
        System.assertEquals(product.Id,productFromDatabse.Id);
    }

}