force-app/main/default/objects/Product2/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <label>Producer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>Lenovo</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Philips</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Xiaomi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PW_CustomSearchCommunityControllerTest.cls
@IsTest
public with sharing class PW_CustomSearchCommunityControllerTest {
    @TestSetup
    public static void testSetup() {
        Product2 productTest = new Product2(Name='CPU i5',Model__c='i5-4434',Producer__c='Intel',ProductCode='G88E',isActive=true,Family='CPU');
        insert productTest;
    }

    @IsTest
    public static void shouldReturnNothingSQLInjectionInput() {
        List<Product2> products = PW_CustomSearchCommunityController.searchForIds('%');
        System.assertEquals(0,products.size());
    }

    @IsTest
    public static void shouldReturnIdIntelProduct() {
        Product2 product = [SELECT Id FROM Product2 WHERE ProductCode='G88E'];
        List<Product2> ids = PW_CustomSearchCommunityController.searchForIds('Intel');
        System.assertEquals(product.Id,ids[0].Id);
    }

}