force-app/main/default/objects/Product_Review__c/Product_Review__c.object-meta.xml
<CustomObject>
    <label>Product Review</label>
    <nameField>
        <label>Product Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductReviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Review__c/fields/AcceptReview__c.field-meta.xml
<CustomField>
    <fullName>AcceptReview__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AcceptReview</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Review__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/PW_ProductPage.cls
public without sharing class PW_ProductPage {
    @AuraEnabled(cacheable=true)
    public static List<ContentDocumentLink> getImages(Id recordId){
        String query = 'SELECT Id, ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId = :recordId';
        return Database.query(query);
    }

    @AuraEnabled(cacheable=true)
    public static List<PricebookEntry> getProductPrice(String recordId){
        return [SELECT UnitPrice 
                FROM PricebookEntry 
                WHERE Product2Id =:recordId];
    }

    @AuraEnabled
    public static List<Product_Review__c> getAllReviews(String productId) {
        return [SELECT Id, Name, Comment__c, Rating__c,  LastModifiedDate, AcceptReview__c, CreatedDate, CreatedBy.Name, CreatedBy.SmallPhotoUrl, CreatedById, CreatedBy.PhotoUrl__c
                FROM Product_Review__c
                WHERE Product__c =:productId
                AND AcceptReview__c = true
                ORDER BY CreatedDate DESC];
    }

    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getProductReview(String recordId){
        return [SELECT COUNT(Id) CountRating, 
                AVG(Rating__c) AverageRating 
                FROM Product_Review__c 
                WHERE Product__r.Id = :recordId];
    }

    @AuraEnabled(cacheable=true)
    public static List<Product_Review__c> userHasReviewCheck(Id userID, Id productId){
        return [SELECT Id, CreatedBy.Id, AcceptReview__c FROM Product_Review__c WHERE CreatedBy.Id = :userID AND Product__c = :productId];
    }
}